// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfT_-LkwWTEPQDO5S0x3yVBWtBjOXrtrc',
    appId: '1:956206840069:web:15577da241a09071585f6c',
    messagingSenderId: '956206840069',
    projectId: 'eventeaze-1d998',
    authDomain: 'eventeaze-1d998.firebaseapp.com',
    storageBucket: 'eventeaze-1d998.appspot.com',
    measurementId: 'G-YFC89V76NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwY8vZOybdWNURXQDSORbx1OaNGkGX_t4',
    appId: '1:956206840069:android:a65a452d81249e3d585f6c',
    messagingSenderId: '956206840069',
    projectId: 'eventeaze-1d998',
    storageBucket: 'eventeaze-1d998.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6Zd400oun4ktcllLpYV7Gh31VTfa6V-w',
    appId: '1:956206840069:ios:9ae2b11e49e6374d585f6c',
    messagingSenderId: '956206840069',
    projectId: 'eventeaze-1d998',
    storageBucket: 'eventeaze-1d998.appspot.com',
    iosBundleId: 'com.example.eventEaze',
  );
}
